name: Set Up Cumulus
description: 'Install CumulusCI and sfdx'
inputs:
  cumulusci-version:
    description: 'version of CumulusCI to install'
    required: false
  sfdx-version:
    description: 'version of SFDX to install'
    required: false
runs:
    using: "composite"
    steps:
      - name: Set Installable Versions
        id: versions
        # Note: we do not pin an action tag here. This is deliberate,
        # to allow us flexibility in pinning specific package versions.
        uses: v15h9/default-package-versions@main
        with:
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
      - name: Store Versions
        run: |
          echo '${{ steps.versions.outputs.sfdx-version }}' > actions-sfdx-version.txt
          echo '${{ steps.versions.outputs.cumulusci-version }}' > actions-cci-version.txt
        shell: bash
      - name: Set Up Node 
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: actions-sfdx-version.txt
      - name: Install sfdx
        run: |
          npm install -g 'sfdx-cli@${{ steps.versions.outputs.sfdx-version }}'
        shell: bash
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: actions-cci-version.txt
      - name: Install CumulusCI
        run: |
          pip install 'cumulusci==${{ steps.versions.outputs.cumulusci-version }}'
        shell: bash
